### ISSUE TITLE
Gør sådan man kan læse filen

### ISSUE THREAD

**Issue by Rotendahl** [RusKursusGruppen/vedtaegter#2]
@BeneCollyridam 
Det er  ikke så fedt at man skal clone og compile for at se vedtægterne. 

Jeg synes at vi skal skifte til markdown, så det automatisk er renderet. 
Alternativt kan vi sætte en build process op der compiler tex'en til en pdf, det 
er bare noget mere arbejde. 

Hvad tænker du?

**Comment by BeneCollyridam** [comment]
Det er en rigtig god idé at sætte en build process op men en dårlig idé at
skifte til markdown. Jeg tror, at markdowns funktionalitet er for begrænset
til, at kunne repræsentere vedtægterne korrekt uden for meget arbejde,
hvilket er grunden vi skiftede til TeX.

**Comment by Rotendahl** [comment]
Lukket af #3
